name: Build DLL + Nuget Package

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_check.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Run version check
        id: version_check
        run: |
          chmod +x ./version_check.sh
          ./version_check.sh
  build:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 6 environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'
      - name: Build Settings
        run: dotnet build
      - name: Build NuGet package
        run: dotnet pack --configuration Release
      - name: Upload NuGet package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: bin/Release/*.nupkg
      - name: Upload Thunderstore package
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-package
          path: TootTallyWebsocketLibs.zip
  
  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download NuGet package artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: nuget-package
      - name: Setup .NET 6 environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'
      - name: Push package to NuGet
        run: dotnet nuget push nuget-package/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
